/**
 * Fixed Asset Register export — Xefe's OWN layout.
 *
 * Deliberately designed from first principles (standard register content:
 * cost / accumulated / net book value per asset). Do not imitate any client
 * or firm workbook layout, column order, or styling — this file is the
 * canonical Xefe presentation: brand-green header band, bilingual title,
 * live-register snapshot (not a per-year "mapa").
 */
import type { FixedAsset } from "@/types/accounting";
import { buildSchedule, monthlyCharge } from "@/lib/accounting/depreciation";
import { downloadBlob } from "@/lib/downloadBlob";

const XEFE_GREEN = "FF6A9C29";
const HEADER_GREY = "FFF3F4F6";

const round2 = (n: number) => Math.round(n * 100) / 100;

export interface RegisterLabels {
  /** assetClass enum key -> display label (falls back to a humanized key). */
  classLabels?: Record<string, string>;
  statusActive?: string;
  statusFullyDepreciated?: string;
  statusDisposed?: string;
}

/** "fixed_term" -> "Fixed term" — last-resort display for an unmapped enum key. */
function humanizeKey(key: string): string {
  const words = key.replace(/[_-]+/g, " ").trim();
  return words ? words.charAt(0).toUpperCase() + words.slice(1) : key;
}

export async function exportFixedAssetRegister(
  assets: FixedAsset[],
  options: { companyName: string; asOf: string; labels?: RegisterLabels },
): Promise<void> {
  const labels = options.labels || {};
  const { default: ExcelJSLib } = await import("exceljs");
  const wb = new ExcelJSLib.Workbook();
  wb.creator = "Xefe";
  const ws = wb.addWorksheet("Fixed Asset Register", {
    pageSetup: {
      orientation: "landscape",
      fitToPage: true,
      fitToWidth: 1,
      fitToHeight: 0,
    },
  });

  // ── Xefe-branded header band ──────────────────────────────────────────
  ws.mergeCells("A1:K1");
  const title = ws.getCell("A1");
  title.value = "Fixed Asset Register · Registu Ativu Fixu";
  title.font = { bold: true, size: 14, color: { argb: "FFFFFFFF" } };
  title.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: XEFE_GREEN },
  };
  title.alignment = { vertical: "middle", horizontal: "left", indent: 1 };
  ws.getRow(1).height = 26;

  ws.mergeCells("A2:K2");
  const subtitle = ws.getCell("A2");
  subtitle.value = `${options.companyName}  ·  as of ${options.asOf}  ·  generated by Xefe (xefe.tl)`;
  subtitle.font = { size: 10, color: { argb: "FF6B7280" } };
  subtitle.alignment = { vertical: "middle", horizontal: "left", indent: 1 };

  // ── column model ──────────────────────────────────────────────────────
  const HEADERS = [
    { key: "reference", label: "Ref", width: 10 },
    { key: "name", label: "Asset", width: 32 },
    { key: "assetClass", label: "Class", width: 14 },
    { key: "acquisitionDate", label: "Acquired", width: 12 },
    { key: "cost", label: "Cost", width: 12 },
    { key: "residual", label: "Residual", width: 11 },
    { key: "life", label: "Life (months)", width: 12 },
    { key: "monthly", label: "Monthly charge", width: 14 },
    { key: "accumulated", label: "Accumulated", width: 13 },
    { key: "nbv", label: "Net book value", width: 14 },
    { key: "status", label: "Status", width: 14 },
  ];
  HEADERS.forEach((h, i) => {
    ws.getColumn(i + 1).width = h.width;
  });

  const headerRow = ws.getRow(4);
  HEADERS.forEach((h, i) => {
    const cell = headerRow.getCell(i + 1);
    cell.value = h.label;
    cell.font = { bold: true, size: 10 };
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: HEADER_GREY },
    };
    cell.border = { bottom: { style: "thin", color: { argb: "FF9CA3AF" } } };
  });

  // ── rows ──────────────────────────────────────────────────────────────
  const money = "#,##0.00";
  let rowIndex = 5;
  for (const asset of assets) {
    const row = ws.getRow(rowIndex++);
    const nbv = round2(
      asset.acquisitionCost - (asset.accumulatedDepreciation || 0),
    );
    row.getCell(1).value = asset.reference || "";
    row.getCell(2).value = asset.name;
    row.getCell(3).value =
      labels.classLabels?.[asset.assetClass] ?? humanizeKey(asset.assetClass);
    row.getCell(4).value = asset.acquisitionDate;
    row.getCell(5).value = asset.acquisitionCost;
    row.getCell(6).value = asset.residualValue || 0;
    row.getCell(7).value = asset.usefulLifeMonths;
    row.getCell(8).value = monthlyCharge(asset);
    row.getCell(9).value = asset.accumulatedDepreciation || 0;
    row.getCell(10).value = nbv;
    row.getCell(11).value =
      asset.status === "disposed"
        ? `${labels.statusDisposed ?? "Disposed"} ${asset.disposalDate || ""}`.trim()
        : asset.status === "fully_depreciated"
          ? (labels.statusFullyDepreciated ?? "Fully depreciated")
          : (labels.statusActive ?? "Active");
    [5, 6, 8, 9, 10].forEach((c) => {
      row.getCell(c).numFmt = money;
    });
    if (asset.status === "disposed") {
      row.font = { color: { argb: "FF9CA3AF" } };
    }
  }

  // ── totals (live assets only) ─────────────────────────────────────────
  const live = assets.filter((a) => a.status !== "disposed");
  const totalsRow = ws.getRow(rowIndex + 1);
  totalsRow.getCell(2).value = `Totals (${live.length} assets in service)`;
  totalsRow.getCell(2).font = { bold: true };
  totalsRow.getCell(5).value = round2(
    live.reduce((s, a) => s + a.acquisitionCost, 0),
  );
  totalsRow.getCell(9).value = round2(
    live.reduce((s, a) => s + (a.accumulatedDepreciation || 0), 0),
  );
  totalsRow.getCell(10).value = round2(
    live.reduce(
      (s, a) => s + a.acquisitionCost - (a.accumulatedDepreciation || 0),
      0,
    ),
  );
  [5, 9, 10].forEach((c) => {
    const cell = totalsRow.getCell(c);
    cell.numFmt = money;
    cell.font = { bold: true };
    cell.border = { top: { style: "thin" }, bottom: { style: "double" } };
  });

  // ── per-asset schedule sheet (active assets) ──────────────────────────
  const scheduleSheet = wb.addWorksheet("Depreciation Schedules");
  let sRow = 1;
  for (const asset of assets.filter(
    (a) => a.status !== "disposed" && a.usefulLifeMonths > 0,
  )) {
    const head = scheduleSheet.getRow(sRow++);
    head.getCell(1).value =
      `${asset.name}${asset.reference ? ` (${asset.reference})` : ""}`;
    head.getCell(1).font = { bold: true, color: { argb: "FFFFFFFF" } };
    head.getCell(1).fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: XEFE_GREEN },
    };
    scheduleSheet.mergeCells(sRow - 1, 1, sRow - 1, 4);

    const cols = scheduleSheet.getRow(sRow++);
    ["Period", "Charge", "Accumulated", "Net book value"].forEach(
      (label, i) => {
        const cell = cols.getCell(i + 1);
        cell.value = label;
        cell.font = { bold: true, size: 9 };
        cell.fill = {
          type: "pattern",
          pattern: "solid",
          fgColor: { argb: HEADER_GREY },
        };
      },
    );

    for (const line of buildSchedule(asset)) {
      const row = scheduleSheet.getRow(sRow++);
      row.getCell(1).value = line.period;
      row.getCell(2).value = line.charge;
      row.getCell(3).value = line.accumulated;
      row.getCell(4).value = line.netBookValue;
      [2, 3, 4].forEach((c) => {
        row.getCell(c).numFmt = money;
      });
      if (
        asset.depreciatedThroughPeriod &&
        line.period <= asset.depreciatedThroughPeriod
      ) {
        row.font = { color: { argb: "FF9CA3AF" } };
      }
    }
    sRow++; // spacer
  }
  [14, 12, 13, 14].forEach((w, i) => {
    scheduleSheet.getColumn(i + 1).width = w;
  });

  // ── download ──────────────────────────────────────────────────────────
  const buffer = await wb.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  // Shared helper: appends the anchor and delays revokeObjectURL so Safari
  // can finish reading the blob (a synchronous revoke intermittently yields
  // an empty download there).
  downloadBlob(blob, `Xefe_Fixed_Asset_Register_${options.asOf}.xlsx`);
}
