/**
 * Payslip wording shared by the PDF renderer and lightweight HTML previews.
 * Keep this module free of React/PDF imports so marketing pages do not pull the
 * PDF rendering toolchain into the initial application bundle.
 */
export type PayslipLocale = "en" | "tet" | "pt";

export const payslipStrings: Record<PayslipLocale, Record<string, string>> = {
  en: {
    title: "EARNINGS STATEMENT",
    payDate: "Pay Date:",
    period: "Period:",
    employeeInfo: "Employee Information",
    name: "Name:",
    employeeId: "Employee ID:",
    department: "Department:",
    position: "Position:",
    payInfo: "Pay Information",
    payFrequency: "Pay Frequency:",
    hourlyRate: "Hourly Rate:",
    overtimeRate: "Overtime Rate:",
    regular: "REGULAR",
    overtime: "OVERTIME",
    doubleTime: "DOUBLE TIME",
    holiday: "HOLIDAY",
    ptoUsed: "PTO USED",
    sickUsed: "SICK USED",
    hrs: "hrs",
    earnings: "Earnings",
    description: "Description",
    hours: "Hours",
    rate: "Rate",
    amount: "Amount",
    grossPay: "Gross Pay",
    deductions: "Deductions",
    preTax: "(Pre-tax)",
    totalDeductions: "Total Deductions",
    netPay: "Net Pay",
    ytdSummary: "Year-to-Date Summary",
    ytdGrossPay: "YTD Gross Pay",
    ytdNetPay: "YTD Net Pay",
    ytdWIT: "YTD WIT",
    ytdINSS: "YTD INSS (Employee)",
    employerContributions: "Employer Contributions",
    employerINSS: "INSS Employer (6%)",
    totalEmployerCost: "Total Employer Cost",
    employerNote:
      "The following contributions are paid by the employer and are not deducted from your pay.",
    subsidioAnualAccrual: "13th Month Accrual",
    subsidioAnualNote:
      "Monthly accrual towards your Subsidio Anual (13th month salary), paid annually.",
    perMonth: "/month",
    footer: "This is a computer-generated document. No signature is required.",
    footerContact: "For questions about your pay, please contact HR at",
    code: "Code",
    ref: "Ref.",
    earningsCol: "Earnings",
    deductionsCol: "Deductions",
    totalEarnings: "Total Earnings",
    monthOf: "Month of",
    payslipTitleRow: "Salary Payment Receipt",
    auditBaseSalary: "Base Salary",
    auditAbsences: "Absences",
    auditCommissions: "Commissions",
    auditAllowances: "Allowances",
    auditTaxableBase: "Taxable Base",
    auditTaxOfMonth: "Tax of Month",
    auditSocialSecurity: "Social Security",
    auditOtherDeductions: "Other Deductions",
    copyMark: "COPY",
    signatureDeclaration:
      "I acknowledge receipt of the net amount itemised in this pay slip.",
    signatureLabel: "EMPLOYEE SIGNATURE",
    signatureDate: "Date:",
  },
  tet: {
    title: "DEKLARASAUN RENDIMENTU",
    payDate: "Data Pagamentu:",
    period: "Períodu:",
    employeeInfo: "Informasaun Trabalhador",
    name: "Naran:",
    employeeId: "ID Trabalhador:",
    department: "Departamentu:",
    position: "Pozisaun:",
    payInfo: "Informasaun Pagamentu",
    payFrequency: "Frequénsia Pagamentu:",
    hourlyRate: "Taxa Oras:",
    overtimeRate: "Taxa Hora Extra:",
    regular: "REGULÁR",
    overtime: "HORA EXTRA",
    doubleTime: "DOBRU",
    holiday: "FERIADU",
    ptoUsed: "LISENSA",
    sickUsed: "MORAS",
    hrs: "oras",
    earnings: "Rendimentu",
    description: "Deskrisaun",
    hours: "Oras",
    rate: "Taxa",
    amount: "Montante",
    grossPay: "Saláriu Brutu",
    deductions: "Dedusaun",
    preTax: "(Molok impostu)",
    totalDeductions: "Dedusaun Totál",
    netPay: "Saláriu Líkidu",
    ytdSummary: "Rezumu Tinan Tomak",
    ytdGrossPay: "Brutu Tinan Tomak",
    ytdNetPay: "Líkidu Tinan Tomak",
    ytdWIT: "WIT Tinan Tomak",
    ytdINSS: "INSS Tinan Tomak (Trabalhador)",
    employerContributions: "Kontribuisaun Empreza",
    employerINSS: "INSS Empreza (6%)",
    totalEmployerCost: "Kustu Totál Empreza",
    employerNote:
      "Kontribuisaun tuir mai selu husi empreza no la halo dedusaun husi ita-nia saláriu.",
    subsidioAnualAccrual: "Akumulasaun Fulan-13",
    subsidioAnualNote:
      "Akumulasaun mensal ba ita-nia Subsídiu Anuál (saláriu fulan-13), selu tinan-tinan.",
    perMonth: "/fulan",
    footer: "Dokumentu ne'e halo husi komputador. La presiza asinatura.",
    footerContact: "Se iha dúvida kona-ba ita-nia pagamentu, kontaktu RH iha",
    code: "Kódigu",
    ref: "Ref.",
    earningsCol: "Rendimentu",
    deductionsCol: "Dedusaun",
    totalEarnings: "Rendimentu Totál",
    monthOf: "Fulan",
    payslipTitleRow: "Resibu Pagamentu Saláriu",
    auditBaseSalary: "Saláriu Báziku",
    auditAbsences: "Falta",
    auditCommissions: "Komisaun",
    auditAllowances: "Subsídiu",
    auditTaxableBase: "Báze Impostu",
    auditTaxOfMonth: "Impostu Fulan",
    auditSocialSecurity: "Seguransa Sosiál",
    auditOtherDeductions: "Dedusaun Seluk",
    copyMark: "KÓPIA",
    signatureDeclaration:
      "Hau rekonese simu montante líkidu ne'ebé deskrimina iha resibu ne'e.",
    signatureLabel: "ASINATURA TRABALHADOR",
    signatureDate: "Data:",
  },
  pt: {
    title: "RECIBO DE VENCIMENTO",
    payDate: "Data de Pagamento:",
    period: "Período:",
    employeeInfo: "Informação do Trabalhador",
    name: "Nome:",
    employeeId: "Código Trabalhador:",
    department: "Departamento:",
    position: "Cargo:",
    payInfo: "Informação de Pagamento",
    payFrequency: "Frequência:",
    hourlyRate: "Valor Hora:",
    overtimeRate: "Valor Hora Extra:",
    regular: "REGULAR",
    overtime: "HORAS EXTRAS",
    doubleTime: "DOBRO",
    holiday: "FERIADO",
    ptoUsed: "FÉRIAS",
    sickUsed: "DOENÇA",
    hrs: "h",
    earnings: "Vencimentos",
    description: "Descrição",
    hours: "Horas",
    rate: "Taxa",
    amount: "Montante",
    grossPay: "Vencimento Bruto",
    deductions: "Descontos",
    preTax: "(Pré-impostos)",
    totalDeductions: "Total de Descontos",
    netPay: "Valor Líquido",
    ytdSummary: "Resumo Ano Atual",
    ytdGrossPay: "Bruto Acumulado",
    ytdNetPay: "Líquido Acumulado",
    ytdWIT: "Imposto Acumulado",
    ytdINSS: "INSS Acumulado (Trabalhador)",
    employerContributions: "Contribuições do Empregador",
    employerINSS: "INSS Empregador (6%)",
    totalEmployerCost: "Custo Total do Empregador",
    employerNote:
      "As contribuições abaixo são pagas pelo empregador e não são descontadas do seu vencimento.",
    subsidioAnualAccrual: "Acumulação do 13.º Mês",
    subsidioAnualNote:
      "Acumulação mensal do Subsídio Anual (13.º mês), pago anualmente.",
    perMonth: "/mês",
    footer: "Este documento é gerado por computador. Não requer assinatura.",
    footerContact: "Para dúvidas sobre o seu pagamento contacte RH em",
    code: "Cód.",
    ref: "Ref.",
    earningsCol: "Vencimentos",
    deductionsCol: "Descontos",
    totalEarnings: "Total de Vencimentos",
    monthOf: "Mês de",
    payslipTitleRow: "Recibo de Pagamento de Salário",
    auditBaseSalary: "Salário Base",
    auditAbsences: "Faltas",
    auditCommissions: "Comissões",
    auditAllowances: "Subsídios",
    auditTaxableBase: "Base Impostos",
    auditTaxOfMonth: "Imposto do Mês",
    auditSocialSecurity: "Seg. Social",
    auditOtherDeductions: "Descontos",
    copyMark: "CÓPIA",
    signatureDeclaration:
      "Declaro ter recebido a importância líquida discriminada neste recibo.",
    signatureLabel: "ASSINATURA DO FUNCIONÁRIO",
    signatureDate: "Data:",
  },
};
